name: Auto Fix Python Code

on:
  pull_request:
    branches:
      - main  # Change this if your default branch is different

jobs:
  auto-fix:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch full history so git diff works

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Adjust based on your compatibility

      - name: Install dependencies
        run: pip install black flake8  # Add other needed dependencies

      - name: Get changed Python files
        id: changed-files
        run: |
          echo "FILES=$(git diff --name-only --diff-filter=AM origin/main...HEAD | grep '\.py$' || echo '')" >> $GITHUB_ENV

      - name: Run auto-fixer
        if: env.FILES != ''
        run: python auto_fix.py $FILES

      - name: Commit and push fixes
        if: env.FILES != ''
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add $FILES
          git commit -m "Auto-fix: Applied formatting and syntax fixes" || exit 0
          git push
