name: Auto Fix PR Code

on:
  pull_request:
    branches:
      - main  # Change this if using another branch

jobs:
  auto-fix:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install black bandit

      - name: Run Fix Script
        run: |
          python auto_fix.py $(git diff --name-only --diff-filter=AM HEAD~1)

      - name: Commit and push fixes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .
          git commit -m "Auto-fixed Python code formatting and syntax" || echo "No changes to commit"
          git push
