name: LLM Code Review

on:
  pull_request:
    types:
      - opened
      - synchronize
  workflow_run:
    workflows: ["auto-fix"]
    types:
      - completed

jobs:
  review_code:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write  # Needed to post comments

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full history is fetched
          ref: ${{ github.event.pull_request.head.ref }}  

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r req.txt  # Change to requirements.txt if needed

      - name: Run LLM Code Review
        id: llm_review
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          set -x  # Debug mode
          python llm.py || echo "LLM review script failed"
          
          if [ ! -s "llm_output.json" ]; then
            echo "No review output found."
            exit 0  # Do not fail workflow if output is empty
          fi

      - name: Extract PR Number
        id: get_pr
        run: echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV

      - name: Post PR Comment
        if: env.PR_NUMBER != ''
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const llm_output = fs.readFileSync('llm_output.json', 'utf8').trim();

            if (!llm_output) {
              console.log("⚠️ No output from LLM script.");
              return;
            }

            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: process.env.PR_NUMBER,
              body: "### 🤖 LLM Code Review Feedback\n```\n" + llm_output + "\n```"
            });
