name: LLM Code Review

on:
  pull_request:
    types:
      - opened
      - synchronize

  workflow_run:
    workflows: ["auto-fix"]
    types:
      - completed

jobs:
  review_code:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write  # Needed to post comments

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r req.txt

      - name: Load environment variables
        run: echo "API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV

      - name: Run LLM Code Review
        run:  python llm.py > llm_output.json

      - name: Extract PR Number
        id: get_pr
        run: |
          PR_NUMBER=$(jq -r '.pull_request.number // empty' "$GITHUB_EVENT_PATH")
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV
        env:
          GITHUB_EVENT_PATH: ${{ github.event_path }}

      - name: Post PR Comment
        if: env.PR_NUMBER != ''
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { execSync } = require('child_process');

            // Run llm.py and capture output
            const llm_output = execSync('python llm.py', { encoding: 'utf8' }).trim();

            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: process.env.PR_NUMBER,
              body: "```\n" + llm_output + "\n```"
            });